namespace EasyKeys.Shipping.FedEx.Rates
{
    public enum ServiceType
    {
        DEFAULT,

        EUROPE_FIRST_INTERNATIONAL_PRIORITY,

        FEDEX_1_DAY_FREIGHT,

        FEDEX_2_DAY,

        FEDEX_2_DAY_AM,

        FEDEX_2_DAY_FREIGHT,

        FEDEX_3_DAY_FREIGHT,

        FEDEX_EXPRESS_SAVER,

        FEDEX_FIRST_FREIGHT,

        FEDEX_FREIGHT_ECONOMY,

        FEDEX_FREIGHT_PRIORITY,

        FEDEX_GROUND,

        FIRST_OVERNIGHT,

        GROUND_HOME_DELIVERY,

        INTERNATIONAL_ECONOMY,

        INTERNATIONAL_ECONOMY_FREIGHT,

        INTERNATIONAL_FIRST,

        INTERNATIONAL_PRIORITY,

        INTERNATIONAL_PRIORITY_FREIGHT,

        PRIORITY_OVERNIGHT,

        SMART_POST,

        STANDARD_OVERNIGHT,
    }
}
