version: 1.1.{build}
branches:
    only:
      - master
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
## temporary until 5.0.100 sdk is installed
install:
  - ps: $urlCurrent = "https://dotnetcli.blob.core.windows.net/dotnet/Sdk/5.0.100/dotnet-sdk-5.0.100-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::GetTempFileName()
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

nuget:
  disable_publish_on_pr: true

build_script:
  - ps: dotnet nuget locals --clear all
  - ps: dotnet restore EasyKeys.Extensions.sln -v quiet
  - ps: dotnet build EasyKeys.Extensions.sln  --no-restore -p:configuration=Release -p:Version=$($env:appveyor_build_version) -p:GeneratePackageOnBuild=true
  - ps: dotnet pack EasyKeys.Extensions.sln  --no-build -p:configuration=Release -p:Version=$($env:appveyor_build_version) -o packages

#test_script:
  - ps: dotnet test test/EasyKeys.Extensions.UnitTest/EasyKeys.Extensions.UnitTest.csproj -c Release --no-build

artifacts:
- path: .\packages\**\*.nupkg
  name: NuGet package

deploy:
- provider: NuGet
  artifact: /NuGet/
  api_key:
    secure: su1jOONBfHaouJbkbElPwup2Flboaz4DDlgmuWfx+noS4EJUsej/gtGWVOFjExLm
  on:
    branch: master
