//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadDocumentService_v19
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19", ConfigurationName="UploadDocumentService_v19.UploadDocumentPortType")]
    public interface UploadDocumentPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fedex.com/ws/uploaddocument/v19/uploadDocuments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UploadDocumentService_v19.uploadDocumentsResponse> uploadDocumentsAsync(UploadDocumentService_v19.uploadDocumentsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fedex.com/ws/uploaddocument/v19/uploadImages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<UploadDocumentService_v19.uploadImagesResponse> uploadImagesAsync(UploadDocumentService_v19.uploadImagesRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadDocumentsRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private UploadDocumentsProcessingOptionsRequested processingOptionsField;
        
        private string originCountryCodeField;
        
        private string originStateOrProvinceCodeField;
        
        private string originPostalCodeField;
        
        private string originLocationIdField;
        
        private string destinationCountryCodeField;
        
        private string destinationStateOrProvinceCodeField;
        
        private string destinationPostalCodeField;
        
        private string destinationLocationIdField;
        
        private string folderIdField;
        
        private System.DateTime shipTimestampField;
        
        private bool shipTimestampFieldSpecified;
        
        private CarrierCodeType carrierCodeField;
        
        private bool carrierCodeFieldSpecified;
        
        private DocumentUsageType usageField;
        
        private bool usageFieldSpecified;
        
        private UploadDocumentDetail[] documentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public UploadDocumentsProcessingOptionsRequested ProcessingOptions
        {
            get
            {
                return this.processingOptionsField;
            }
            set
            {
                this.processingOptionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OriginCountryCode
        {
            get
            {
                return this.originCountryCodeField;
            }
            set
            {
                this.originCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OriginStateOrProvinceCode
        {
            get
            {
                return this.originStateOrProvinceCodeField;
            }
            set
            {
                this.originStateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OriginPostalCode
        {
            get
            {
                return this.originPostalCodeField;
            }
            set
            {
                this.originPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OriginLocationId
        {
            get
            {
                return this.originLocationIdField;
            }
            set
            {
                this.originLocationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DestinationCountryCode
        {
            get
            {
                return this.destinationCountryCodeField;
            }
            set
            {
                this.destinationCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DestinationStateOrProvinceCode
        {
            get
            {
                return this.destinationStateOrProvinceCodeField;
            }
            set
            {
                this.destinationStateOrProvinceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DestinationPostalCode
        {
            get
            {
                return this.destinationPostalCodeField;
            }
            set
            {
                this.destinationPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DestinationLocationId
        {
            get
            {
                return this.destinationLocationIdField;
            }
            set
            {
                this.destinationLocationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FolderId
        {
            get
            {
                return this.folderIdField;
            }
            set
            {
                this.folderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime ShipTimestamp
        {
            get
            {
                return this.shipTimestampField;
            }
            set
            {
                this.shipTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipTimestampSpecified
        {
            get
            {
                return this.shipTimestampFieldSpecified;
            }
            set
            {
                this.shipTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public CarrierCodeType CarrierCode
        {
            get
            {
                return this.carrierCodeField;
            }
            set
            {
                this.carrierCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierCodeSpecified
        {
            get
            {
                return this.carrierCodeFieldSpecified;
            }
            set
            {
                this.carrierCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public DocumentUsageType Usage
        {
            get
            {
                return this.usageField;
            }
            set
            {
                this.usageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UsageSpecified
        {
            get
            {
                return this.usageFieldSpecified;
            }
            set
            {
                this.usageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Documents", Order=17)]
        public UploadDocumentDetail[] Documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class WebAuthenticationDetail
    {
        
        private WebAuthenticationCredential parentCredentialField;
        
        private WebAuthenticationCredential userCredentialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationCredential ParentCredential
        {
            get
            {
                return this.parentCredentialField;
            }
            set
            {
                this.parentCredentialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public WebAuthenticationCredential UserCredential
        {
            get
            {
                return this.userCredentialField;
            }
            set
            {
                this.userCredentialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class WebAuthenticationCredential
    {
        
        private string keyField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class ImageUploadStatusDetail
    {
        
        private ImageId idField;
        
        private bool idFieldSpecified;
        
        private UploadImageStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private UploadImageStatusInfoType statusInfoField;
        
        private bool statusInfoFieldSpecified;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ImageId Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public UploadImageStatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UploadImageStatusInfoType StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusInfoSpecified
        {
            get
            {
                return this.statusInfoFieldSpecified;
            }
            set
            {
                this.statusInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum ImageId
    {
        
        /// <remarks/>
        IMAGE_1,
        
        /// <remarks/>
        IMAGE_2,
        
        /// <remarks/>
        IMAGE_3,
        
        /// <remarks/>
        IMAGE_4,
        
        /// <remarks/>
        IMAGE_5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadImageStatusType
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        SUCCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadImageStatusInfoType
    {
        
        /// <remarks/>
        IMAGE_EXCEEDS_MAX_RESOLUTION,
        
        /// <remarks/>
        IMAGE_EXCEEDS_MAX_SIZE,
        
        /// <remarks/>
        IMAGE_FAILED_VIRUS_CHECK,
        
        /// <remarks/>
        IMAGE_ID_INVALID,
        
        /// <remarks/>
        IMAGE_ID_MISSING,
        
        /// <remarks/>
        IMAGE_MISSING,
        
        /// <remarks/>
        IMAGE_TYPE_INVALID,
        
        /// <remarks/>
        IMAGE_TYPE_MISSING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadImagesReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private ImageUploadStatusDetail[] imageStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageStatuses", Order=4)]
        public ImageUploadStatusDetail[] ImageStatuses
        {
            get
            {
                return this.imageStatusesField;
            }
            set
            {
                this.imageStatusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum NotificationSeverityType
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        NOTE,
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        WARNING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class Notification
    {
        
        private NotificationSeverityType severityField;
        
        private bool severityFieldSpecified;
        
        private string sourceField;
        
        private string codeField;
        
        private string messageField;
        
        private string localizedMessageField;
        
        private NotificationParameter[] messageParametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeveritySpecified
        {
            get
            {
                return this.severityFieldSpecified;
            }
            set
            {
                this.severityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocalizedMessage
        {
            get
            {
                return this.localizedMessageField;
            }
            set
            {
                this.localizedMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MessageParameters", Order=5)]
        public NotificationParameter[] MessageParameters
        {
            get
            {
                return this.messageParametersField;
            }
            set
            {
                this.messageParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class NotificationParameter
    {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class TransactionDetail
    {
        
        private string customerTransactionIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerTransactionId
        {
            get
            {
                return this.customerTransactionIdField;
            }
            set
            {
                this.customerTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class Localization
    {
        
        private string languageCodeField;
        
        private string localeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LocaleCode
        {
            get
            {
                return this.localeCodeField;
            }
            set
            {
                this.localeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class VersionId
    {
        
        private string serviceIdField;
        
        private int majorField;
        
        private int intermediateField;
        
        private int minorField;
        
        public VersionId()
        {
            this.serviceIdField = "cdus";
            this.majorField = 19;
            this.intermediateField = 0;
            this.minorField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Intermediate
        {
            get
            {
                return this.intermediateField;
            }
            set
            {
                this.intermediateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadImageDetail
    {
        
        private ImageId idField;
        
        private bool idFieldSpecified;
        
        private byte[] imageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ImageId Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadImagesRequest
    {
        
        private WebAuthenticationDetail webAuthenticationDetailField;
        
        private ClientDetail clientDetailField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private UploadImageDetail[] imagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public WebAuthenticationDetail WebAuthenticationDetail
        {
            get
            {
                return this.webAuthenticationDetailField;
            }
            set
            {
                this.webAuthenticationDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ClientDetail ClientDetail
        {
            get
            {
                return this.clientDetailField;
            }
            set
            {
                this.clientDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Images", Order=4)]
        public UploadImageDetail[] Images
        {
            get
            {
                return this.imagesField;
            }
            set
            {
                this.imagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class ClientDetail
    {
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private string integratorIdField;
        
        private Localization localizationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MeterNumber
        {
            get
            {
                return this.meterNumberField;
            }
            set
            {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IntegratorId
        {
            get
            {
                return this.integratorIdField;
            }
            set
            {
                this.integratorIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Localization Localization
        {
            get
            {
                return this.localizationField;
            }
            set
            {
                this.localizationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class DocumentGenerationDetail
    {
        
        private EnterpriseDocumentType typeField;
        
        private bool typeFieldSpecified;
        
        private string minimumCopiesRequiredField;
        
        private RequirementType letterheadField;
        
        private bool letterheadFieldSpecified;
        
        private RequirementType electronicSignatureField;
        
        private bool electronicSignatureFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EnterpriseDocumentType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=1)]
        public string MinimumCopiesRequired
        {
            get
            {
                return this.minimumCopiesRequiredField;
            }
            set
            {
                this.minimumCopiesRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RequirementType Letterhead
        {
            get
            {
                return this.letterheadField;
            }
            set
            {
                this.letterheadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LetterheadSpecified
        {
            get
            {
                return this.letterheadFieldSpecified;
            }
            set
            {
                this.letterheadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RequirementType ElectronicSignature
        {
            get
            {
                return this.electronicSignatureField;
            }
            set
            {
                this.electronicSignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectronicSignatureSpecified
        {
            get
            {
                return this.electronicSignatureFieldSpecified;
            }
            set
            {
                this.electronicSignatureFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum EnterpriseDocumentType
    {
        
        /// <remarks/>
        AIR_WAYBILL,
        
        /// <remarks/>
        CERTIFICATE_OF_ORIGIN,
        
        /// <remarks/>
        COMMERCIAL_INVOICE,
        
        /// <remarks/>
        PRO_FORMA_INVOICE,
        
        /// <remarks/>
        USMCA_CERTIFICATION_OF_ORIGIN,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PRO_FORMA_INVOICE")]
        PRO_FORMA_INVOICE1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum RequirementType
    {
        
        /// <remarks/>
        OPTIONAL,
        
        /// <remarks/>
        PROHIBITED,
        
        /// <remarks/>
        REQUIRED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class DocumentRequirementsDetail
    {
        
        private RequiredDocumentType[] requiredDocumentsField;
        
        private DocumentGenerationDetail[] generationDetailsField;
        
        private EnterpriseDocumentType[] prohibitedDocumentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequiredDocuments", Order=0)]
        public RequiredDocumentType[] RequiredDocuments
        {
            get
            {
                return this.requiredDocumentsField;
            }
            set
            {
                this.requiredDocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GenerationDetails", Order=1)]
        public DocumentGenerationDetail[] GenerationDetails
        {
            get
            {
                return this.generationDetailsField;
            }
            set
            {
                this.generationDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProhibitedDocuments", Order=2)]
        public EnterpriseDocumentType[] ProhibitedDocuments
        {
            get
            {
                return this.prohibitedDocumentsField;
            }
            set
            {
                this.prohibitedDocumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum RequiredDocumentType
    {
        
        /// <remarks/>
        AIR_WAYBILL,
        
        /// <remarks/>
        CERTIFICATE_OF_ORIGIN,
        
        /// <remarks/>
        COMMERCIAL_INVOICE,
        
        /// <remarks/>
        COMMERCIAL_OR_PRO_FORMA_INVOICE,
        
        /// <remarks/>
        USMCA_CERTIFICATE_OF_ORIGIN,
        
        /// <remarks/>
        PRO_FORMA_INVOICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadDocumentStatusDetail
    {
        
        private string lineNumberField;
        
        private string customerReferenceField;
        
        private UploadDocumentProducerType documentProducerField;
        
        private bool documentProducerFieldSpecified;
        
        private UploadDocumentType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string fileNameField;
        
        private UploadDocumentStatusType statusField;
        
        private bool statusFieldSpecified;
        
        private UploadDocumentStatusInfoType statusInfoField;
        
        private bool statusInfoFieldSpecified;
        
        private string messageField;
        
        private string documentIdField;
        
        private UploadDocumentIdProducer documentIdProducerField;
        
        private bool documentIdProducerFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerReference
        {
            get
            {
                return this.customerReferenceField;
            }
            set
            {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UploadDocumentProducerType DocumentProducer
        {
            get
            {
                return this.documentProducerField;
            }
            set
            {
                this.documentProducerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentProducerSpecified
        {
            get
            {
                return this.documentProducerFieldSpecified;
            }
            set
            {
                this.documentProducerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public UploadDocumentType DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentTypeSpecified
        {
            get
            {
                return this.documentTypeFieldSpecified;
            }
            set
            {
                this.documentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public UploadDocumentStatusType Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public UploadDocumentStatusInfoType StatusInfo
        {
            get
            {
                return this.statusInfoField;
            }
            set
            {
                this.statusInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusInfoSpecified
        {
            get
            {
                return this.statusInfoFieldSpecified;
            }
            set
            {
                this.statusInfoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DocumentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public UploadDocumentIdProducer DocumentIdProducer
        {
            get
            {
                return this.documentIdProducerField;
            }
            set
            {
                this.documentIdProducerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentIdProducerSpecified
        {
            get
            {
                return this.documentIdProducerFieldSpecified;
            }
            set
            {
                this.documentIdProducerFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentProducerType
    {
        
        /// <remarks/>
        CUSTOMER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentType
    {
        
        /// <remarks/>
        CERTIFICATE_OF_ORIGIN,
        
        /// <remarks/>
        COMMERCIAL_INVOICE,
        
        /// <remarks/>
        ETD_LABEL,
        
        /// <remarks/>
        OTHER,
        
        /// <remarks/>
        PRO_FORMA_INVOICE,
        
        /// <remarks/>
        USMCA_CERTIFICATION_OF_ORIGIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentStatusType
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        SUCCESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentStatusInfoType
    {
        
        /// <remarks/>
        DOCUMENT_CONTENT_FAILED_VIRUS_CHECK,
        
        /// <remarks/>
        DOCUMENT_CONTENT_MISSING,
        
        /// <remarks/>
        DOCUMENT_CONTENT_TOO_LARGE,
        
        /// <remarks/>
        DOCUMENT_FILE_NAME_MISSING,
        
        /// <remarks/>
        DOCUMENT_FORMAT_NOT_SUPPORTED,
        
        /// <remarks/>
        DOCUMENT_ID_INVALID,
        
        /// <remarks/>
        DOCUMENT_ID_MISSING,
        
        /// <remarks/>
        DOCUMENT_TYPE_INVALID,
        
        /// <remarks/>
        DOCUMENT_TYPE_MISSING,
        
        /// <remarks/>
        DOCUMENT_TYPE_NOT_ALLOWED_FOR_ETD,
        
        /// <remarks/>
        ELECTRONIC_CLEARANCE_NOT_ALLOWED_AT_DESTINATION,
        
        /// <remarks/>
        ELECTRONIC_CLEARANCE_NOT_ALLOWED_AT_ORIGIN,
        
        /// <remarks/>
        EXPIRATION_DATE_INVALID,
        
        /// <remarks/>
        FILENAME_TOO_LONG,
        
        /// <remarks/>
        INELIGIBLE_FOR_UPLOAD,
        
        /// <remarks/>
        UNABLE_TO_PROCESS_DOCUMENT,
        
        /// <remarks/>
        UPLOAD_NOT_ATTEMPTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentIdProducer
    {
        
        /// <remarks/>
        CUSTOMER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadDocumentsReply
    {
        
        private NotificationSeverityType highestSeverityField;
        
        private Notification[] notificationsField;
        
        private TransactionDetail transactionDetailField;
        
        private VersionId versionField;
        
        private UploadDocumentStatusDetail[] documentStatusesField;
        
        private DocumentRequirementsDetail documentRequirementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NotificationSeverityType HighestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Notifications", Order=1)]
        public Notification[] Notifications
        {
            get
            {
                return this.notificationsField;
            }
            set
            {
                this.notificationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public TransactionDetail TransactionDetail
        {
            get
            {
                return this.transactionDetailField;
            }
            set
            {
                this.transactionDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public VersionId Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentStatuses", Order=4)]
        public UploadDocumentStatusDetail[] DocumentStatuses
        {
            get
            {
                return this.documentStatusesField;
            }
            set
            {
                this.documentStatusesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DocumentRequirementsDetail DocumentRequirements
        {
            get
            {
                return this.documentRequirementsField;
            }
            set
            {
                this.documentRequirementsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadDocumentDetail
    {
        
        private string lineNumberField;
        
        private string customerReferenceField;
        
        private UploadDocumentType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string fileNameField;
        
        private byte[] documentContentField;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerReference
        {
            get
            {
                return this.customerReferenceField;
            }
            set
            {
                this.customerReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public UploadDocumentType DocumentType
        {
            get
            {
                return this.documentTypeField;
            }
            set
            {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentTypeSpecified
        {
            get
            {
                return this.documentTypeFieldSpecified;
            }
            set
            {
                this.documentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] DocumentContent
        {
            get
            {
                return this.documentContentField;
            }
            set
            {
                this.documentContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified
        {
            get
            {
                return this.expirationDateFieldSpecified;
            }
            set
            {
                this.expirationDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class PostShipmentUploadDetail
    {
        
        private string trackingNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrackingNumber
        {
            get
            {
                return this.trackingNumberField;
            }
            set
            {
                this.trackingNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public partial class UploadDocumentsProcessingOptionsRequested
    {
        
        private UploadDocumentsProcessingOptionType[] optionsField;
        
        private PostShipmentUploadDetail postShipmentUploadDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Options", Order=0)]
        public UploadDocumentsProcessingOptionType[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PostShipmentUploadDetail PostShipmentUploadDetail
        {
            get
            {
                return this.postShipmentUploadDetailField;
            }
            set
            {
                this.postShipmentUploadDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum UploadDocumentsProcessingOptionType
    {
        
        /// <remarks/>
        POST_SHIPMENT_UPLOAD,
        
        /// <remarks/>
        PRE_ETD_ENHANCEMENTS,
        
        /// <remarks/>
        VALIDATE_ONLY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum CarrierCodeType
    {
        
        /// <remarks/>
        FDXC,
        
        /// <remarks/>
        FDXE,
        
        /// <remarks/>
        FDXG,
        
        /// <remarks/>
        FDXO,
        
        /// <remarks/>
        FXCC,
        
        /// <remarks/>
        FXFR,
        
        /// <remarks/>
        FXSP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19")]
    public enum DocumentUsageType
    {
        
        /// <remarks/>
        CUSTOMER_INFORMATION,
        
        /// <remarks/>
        ELECTRONIC_TRADE_DOCUMENTS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocumentsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19", Order=0)]
        public UploadDocumentService_v19.UploadDocumentsRequest UploadDocumentsRequest;
        
        public uploadDocumentsRequest1()
        {
        }
        
        public uploadDocumentsRequest1(UploadDocumentService_v19.UploadDocumentsRequest UploadDocumentsRequest)
        {
            this.UploadDocumentsRequest = UploadDocumentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocumentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19", Order=0)]
        public UploadDocumentService_v19.UploadDocumentsReply UploadDocumentsReply;
        
        public uploadDocumentsResponse()
        {
        }
        
        public uploadDocumentsResponse(UploadDocumentService_v19.UploadDocumentsReply UploadDocumentsReply)
        {
            this.UploadDocumentsReply = UploadDocumentsReply;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadImagesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19", Order=0)]
        public UploadDocumentService_v19.UploadImagesRequest UploadImagesRequest;
        
        public uploadImagesRequest1()
        {
        }
        
        public uploadImagesRequest1(UploadDocumentService_v19.UploadImagesRequest UploadImagesRequest)
        {
            this.UploadImagesRequest = UploadImagesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadImagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fedex.com/ws/uploaddocument/v19", Order=0)]
        public UploadDocumentService_v19.UploadImagesReply UploadImagesReply;
        
        public uploadImagesResponse()
        {
        }
        
        public uploadImagesResponse(UploadDocumentService_v19.UploadImagesReply UploadImagesReply)
        {
            this.UploadImagesReply = UploadImagesReply;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface UploadDocumentPortTypeChannel : UploadDocumentService_v19.UploadDocumentPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UploadDocumentPortTypeClient : System.ServiceModel.ClientBase<UploadDocumentService_v19.UploadDocumentPortType>, UploadDocumentService_v19.UploadDocumentPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UploadDocumentPortTypeClient() : 
                base(UploadDocumentPortTypeClient.GetDefaultBinding(), UploadDocumentPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.UploadDocumentServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UploadDocumentPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(UploadDocumentPortTypeClient.GetBindingForEndpoint(endpointConfiguration), UploadDocumentPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UploadDocumentPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UploadDocumentPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UploadDocumentPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UploadDocumentPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UploadDocumentPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UploadDocumentService_v19.uploadDocumentsResponse> UploadDocumentService_v19.UploadDocumentPortType.uploadDocumentsAsync(UploadDocumentService_v19.uploadDocumentsRequest1 request)
        {
            return base.Channel.uploadDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<UploadDocumentService_v19.uploadDocumentsResponse> uploadDocumentsAsync(UploadDocumentService_v19.UploadDocumentsRequest UploadDocumentsRequest)
        {
            UploadDocumentService_v19.uploadDocumentsRequest1 inValue = new UploadDocumentService_v19.uploadDocumentsRequest1();
            inValue.UploadDocumentsRequest = UploadDocumentsRequest;
            return ((UploadDocumentService_v19.UploadDocumentPortType)(this)).uploadDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UploadDocumentService_v19.uploadImagesResponse> UploadDocumentService_v19.UploadDocumentPortType.uploadImagesAsync(UploadDocumentService_v19.uploadImagesRequest1 request)
        {
            return base.Channel.uploadImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<UploadDocumentService_v19.uploadImagesResponse> uploadImagesAsync(UploadDocumentService_v19.UploadImagesRequest UploadImagesRequest)
        {
            UploadDocumentService_v19.uploadImagesRequest1 inValue = new UploadDocumentService_v19.uploadImagesRequest1();
            inValue.UploadImagesRequest = UploadImagesRequest;
            return ((UploadDocumentService_v19.UploadDocumentPortType)(this)).uploadImagesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UploadDocumentServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UploadDocumentServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://wsbeta.fedex.com/web-services/uploaddocument");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UploadDocumentPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.UploadDocumentServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UploadDocumentPortTypeClient.GetEndpointAddress(EndpointConfiguration.UploadDocumentServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            UploadDocumentServicePort,
        }
    }
}
