
POST https://{{host}}/stamps/createInternationalShipment?ServiceType=USPMI&localhost:7142/stamps/createShipment?ServiceType=USFC&PackageTypeSelected=ThickEnvelope
Content-Type: application/json

{
  "origin": {
    "city": "Charlotte",
    "countryCode": "US",
    "streetLine": "PO Box 411248",
    "streetLine2": null,
    "postalCode": "28241",
    "stateOrProvince": "NC",
    "isResidential": false
  },

  "destination": {
    "city": "St-Dominique",
    "countryCode": "CA",
    "streetLine": "500 7e Rang",
    "streetLine2": null,
    "postalCode": "J0H 1L0",
    "stateOrProvince": "QC",
    "isResidential": false
  },

  "package": {
    "ShipDate" :null,
    "signatureRequiredOnDelivery": false,
    "insuredValue": 100,
    "length": 1.0,
    "width": 0.25,
    "height": 1.0,
    "weight": 19.0
  }
,
  "commodity": {
    "name": "package of keys",
    "numberOfPieces": 1,
    "description": "these are hon 1 keys",
    "countryOfManufacturer": "US",
    "harmonizedCode": "test",
    "quantity": 1,
    "ciMarksandNumbers": "not sure",
    "customsValue": 10,
    "amount": 10,
    "exportLicenseNumber": "dont know number",
    "exportLicenseExpirationDate": "2022-05-14T01:58:52.007Z",
    "comments": "this is a test",
    "additionalMeasures": "test",
    "exiseConditions": "test",
    "partNumber": "test",
    "purpose": "string test"
  }
}
