
@serviceType = USFC
@packageType = Package

@orderId = ek-123456

@isSample = false

@fileName=rates-stamps-domestic-3.json

POST https://{{host}}/stamps/createShipment?serviceType={{serviceType}}&packageType={{packageType}}&orderId={{orderId}}&isSample={{isSample}}
Content-Type: application/json


< ./src/Minimal.Apis/rest/data/{{fileName}}
