
@fileName=rates-stamps-domestic-3.json
#@fileName=rates-stamps-domestic-bulky-1.json


#@fileName = rates-stamps-intl-1.json

POST https://{{host}}/stamps/getRates
Content-Type: application/json

< ./src/Minimal.Apis/rest/data/{{fileName}}
