
POST https://{{host}}/stamps/getRates
Content-Type: application/json


{
  "destination": {
    "city": "Cincinnati",
    "countryCode": "US",
    "streetLine": "3991 kenkel ave",
    "streetLine2": null,
    "postalCode": "45211",
    "stateOrProvince": "OH",
    "isResidential": false
  },

  "origin": {
    "city": "Charlotte",
    "countryCode": "US",
    "streetLine": "PO Box 411248",
    "streetLine2": null,
    "postalCode": "28241",
    "stateOrProvince": "NC",
    "isResidential": false
  },

  "package": {
    "ShipDate" :null,
    "signatureRequiredOnDelivery": false,
    "insuredValue": 0,
    "length": 9.0,
    "width": 9.0,
    "height": 0.5,
    "weight": 0.1
  }
}
