
POST {{host}}/fedex/getRates
Content-Type: application/json

{
  "origin": {
    "city": "Charlotte",
    "countryCode": "US",
    "countryName": "United States",
    "streetLine": "11407 Granite Street ",
    "streetLine2": "Ste B",
    "postalCode": "28273",
    "stateOrProvince": "NC",
    "isResidential": true
  },
  "destination": {
    "countryName": "CA",
    "streetLine": "4997 Carling Avenue",
    "streetLine2": null,
    "city": "Ottawa",
    "stateOrProvince": "ON",
    "postalCode": "K1Z 7B5",
    "countryCode": "CA",
    "isResidential": false
  },
  "package": {
    "shipDate": "2023-04-28T00:34:53.365Z",
    "signatureRequiredOnDelivery": false,
    "insuredValue": 0,
    "length": 9.0,
    "width": 12.0,
    "height": 1.0,
    "weight": "0.9375"
  }
}
