
POST {{host}}/stamps/getRates
Content-Type: application/json

{
  "origin": {
    "city": "Charlotte",
    "countryCode": "US",
    "countryName": "United States",
    "streetLine": "11407 Granite Street ",
    "streetLine2": "Ste B",
    "postalCode": "28273",
    "stateOrProvince": "NC",
    "isResidential": true
  },
  "destination": {
    "countryName": "United States",
    "streetLine": "725 Ponce de Leon Ave NE",
    "streetLine2": null,
    "city": "Atlanta",
    "stateOrProvince": "GA",
    "postalCode": "30306",
    "countryCode": "US",
    "isResidential": false
  },
  "package": {
    "shipDate": "2023-05-11T00:34:53.365Z",
    "signatureRequiredOnDelivery": true,
    "insuredValue": 100,
    "length": 8.0,
    "width": 4.0,
    "height": 1.0,
    "weight": 0.099
  },

  "sender": {
    "firstName": "string",
    "lastName": "string",
    "company": "string",
    "department": "string",
    "email": "string",
    "extension": "string",
    "phoneNumber": "string"
  },
  "recipient": {
    "firstName": "string",
    "lastName": "string",
    "company": "string",
    "department": "string",
    "email": "string",
    "extension": "string",
    "phoneNumber": "string"
  }
}
